import{S as u,i as d}from"./assets/vendor-5ObWk2rO.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const f="47491725-6916c20f65c7c72c223d91484",m="https://pixabay.com/api/";function h(n){const o=`${m}?key=${f}&q=${n}&image_type=photo&orientation=horizontal&safesearch=true`;return console.log("Request URL:",o),fetch(o).then(r=>r.json()).then(r=>{if(r.hits.length===0)throw new Error("No images found");return r.hits}).catch(r=>{throw console.error("Error fetching images:",r),r})}const g=new u(".gallery a");function p(n){const o=document.querySelector(".gallery");o.innerHTML="";const r=n.map(({webformatURL:s,largeImageURL:e,tags:t,likes:i,views:c,comments:a,downloads:l})=>`
        <a href="${e}" class="gallery-item">
          <img src="${s}" alt="${t}" />
          <div class="info">
            <p class="info-item"><b>Likes:</b> ${i}</p>
            <p class="info-item"><b>Views:</b> ${c}</p>
            <p class="info-item"><b>Comments:</b> ${a}</p>
            <p class="info-item"><b>Downloads:</b> ${l}</p>
          </div>
        </a>
      `).join("");o.insertAdjacentHTML("beforeend",r),g.refresh()}function y(){d.error({title:"Sorry",message:"There are no images matching your search query. Please try again!"})}function L(){document.querySelector(".loader").classList.remove("hidden")}function b(){document.querySelector(".loader").classList.add("hidden")}document.addEventListener("DOMContentLoaded",()=>{const n=document.querySelector(".search-form"),o=document.querySelector(".search-input");n.addEventListener("submit",async r=>{r.preventDefault();const s=o.value.trim();if(s===""){iziToast.warning({title:"Warning",message:"Please enter a search term."});return}L();try{console.log("Fetching images for query:",s);const e=await h(s);console.log("Images fetched:",e),ь,p(e)}catch(e){console.error("Error during fetch:",e),y()}finally{b()}})});
//# sourceMappingURL=index.js.map
