import{S as d,i as f}from"./assets/vendor-5ObWk2rO.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const m="47491725-6916c20f65c7c72c223d91484",h="https://pixabay.com/api/";function p(o){const n=`${h}?key=${m}&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(n).then(t=>t.json()).then(t=>{if(t.hits.length===0)throw new Error("No images found");return t.hits}).catch(t=>{throw console.error("Error fetching images:",t),t})}const g=new d(".gallery a");function y(o){const n=document.querySelector(".gallery");if(n.innerHTML="",o.length===0){c();return}const t=o.map(({webformatURL:s,largeImageURL:e,tags:r,likes:i,views:a,comments:l,downloads:u})=>`
        <a href="${e}" class="gallery-item">
          <img src="${s}" alt="${r}" />
          <div class="info">
            <p class="info-item"><b>Likes:</b> ${i}</p>
            <p class="info-item"><b>Views:</b> ${a}</p>
            <p class="info-item"><b>Comments:</b> ${l}</p>
            <p class="info-item"><b>Downloads:</b> ${u}</p>
          </div>
        </a>
      `).join("");n.insertAdjacentHTML("beforeend",t),g.refresh()}function c(){const o=document.querySelector(".gallery");o.innerHTML="",f.error({title:"Sorry",message:"There are no images matching your search query. Please try again!"})}function L(){document.querySelector(".loader").classList.remove("hidden")}function b(){document.querySelector(".loader").classList.add("hidden")}document.addEventListener("DOMContentLoaded",()=>{const o=document.querySelector(".search-form"),n=document.querySelector(".search-input");o.addEventListener("submit",async t=>{t.preventDefault();const s=n.value.trim();if(s===""){iziToast.warning({title:"Warning",message:"Please enter a search term."});return}L();try{const e=await p(s);y(e)}catch{c()}finally{b()}})});
//# sourceMappingURL=index.js.map
